name: Daily Jira Report to Kiotviet Chat

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy lúc 9h VN (UTC+7 = 2h UTC)
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  send_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Jira Daily Report Script
        env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GOOGLE_CHAT_URL: ${{ secrets.GOOGLE_CHAT_URL }}
        run: python jira_daily_report.py
